/**
 * musicScore item
 * @param {String|Array} key - 键位
 * @param {Number?} beat - 节拍
 * @description 音乐乐谱
 */

// // 爱人错过
// const arcg = [
//   { key: "3" },
//   { key: "6-", beat: 0.5 },
//   { key: "1", beat: 1.5 },
//   { key: "0", beat: 0.5 },
//   { key: "4-", beat: 0.5 },
//   { key: "4" },
//   { key: "3", beat: 0.5 },
//   { key: "2" },
//   { key: "3" },
//   { key: "3" },
//   { key: "7-", beat: 0.5 },
//   { key: "7-" },
//   { key: "1" },
//   { key: "7-", beat: 3.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "7-" },
//   { key: "1" , beat: 0.5},
//   { key: "7-", beat: 1.5 },
//   { key: "0", beat: 4 },
//   { key: "3-", beat: 0.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "1", beat: 3 },
//   { key: "7-", beat: 0.5 },
//   { key: "6-", beat: 4.5 },
//   { key: "3" },
//   { key: "6-", beat: 0.5 },
//   { key: "1", beat: 1.5 },
//   { key: "0", beat: 0.5 },
//   { key: "5-", beat: 0.5 },
//   { key: "5-" },
//   { key: "3", beat: 0.5 },
//   { key: "2" },
//   { key: "3" },
//   { key: "5" },
//   { key: "7-", beat: 0.5 },
//   { key: "7-" },
//   { key: "1" },
//   { key: "7-", beat: 3.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "7-" },
//   { key: "1" , beat: 0.5 },
//   { key: "7-", beat: 1.5 },
//   { key: "0", beat: 4 },
//   { key: "3-", beat: 0.5 },
//   { key: "3-", beat: 0.5 },
//   { key: "1", beat: 3 },
//   { key: "7-", beat: 0.5 },
//   { key: "6-", beat: 4.5 },
// ];

// 晴天
const qt_beatTime = 67;
const qt = [
  { key: '6-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '4-', beat: 0.5 },
  { key: '5-', beat: 0.25 },
  { key: '6-', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '1-', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7--', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  /* --------------------- */
  { key: '6-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '6-', beat: 0.5 },
  { key: '4-', beat: 0.5 },
  { key: '5-', beat: 0.25 },
  { key: '6-', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '1-', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7--', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '5-', beat: 0.5 },
  /* --------------------- */
  { key: '6-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '4-', beat: 0.5 },
  { key: '5-', beat: 0.25 },
  { key: '6-', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '1-', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7--', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  /* --------------------- */
  { key: '6-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '6-', beat: 0.5 },
  { key: '4-', beat: 0.5 },
  { key: '5-', beat: 0.25 },
  { key: '6-', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '1-', beat: 0.5 },
  { key: '5-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1-', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7--', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '5-', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1' },
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1' },
  { key: '2', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '2', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '5-', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1' },
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: ['2', '3'] },
  { key: '2', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '4', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '2', beat: 0.25 },
  { key: '4', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '2', beat: 0.25 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '5-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: '1', beat: 0.25 },
  { key: '2', beat: 0.25 },
  /* --------------------- */
  { key: '3', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '2', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '2', beat: 0.5 },
  { key: '1' },
  /* --------------------- */
  { key: '5-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: ['3', '4'], beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: '1', beat: 0.25 },
  { key: '2', beat: 0.25 },
  /* --------------------- */
  { key: ['2', '3'], beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: ['2', '3'], beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '2', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: '2', beat: 0.5 },
  { key: '1', beat: 0.75 },
  { key: '7-', beat: 0.25 },
  /* --------------------- */
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '7-', beat: 0.25 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '7-', beat: 0.25 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '7-', beat: 0.25 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.25 },
  /* --------------------- */
  { key: '0', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '5', beat: 0.25 },
  { key: '4', beat: 0.25 },
  { key: '3', beat: 0.25 },
  { key: ['2', '3'], beat: 2.25 },
  /* --------------------- */
  { key: '0' },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  /* --------------------- */
  { key: '6-', beat: 0.5 },
  { key: '7-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '1', beat: 1.5 },
  /* --------------------- */
  { key: '0' },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: '1', beat: 0.25 },
  { key: ['2', '3'], beat: 0.5 },
  { key: '1', beat: 0.5 },
  /* --------------------- */
  { key: '6-', beat: 0.5 },
  { key: '7-', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: ['1', '2'], beat: 2.5 },
  /* --------------------- */
  { key: '0', beat: 2 },
  /* --------------------- */
  { key: ['2', '3'], beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: ['3', '4'], beat: 0.5 },
  { key: '3' },
  { key: '1', beat: 0.5 },
  { key: ['3', '5'], beat: 0.5 },
  { key: '7', beat: 0.5 },
  /* --------------------- */
  { key: '1+', beat: 0.5 },
  { key: '7', beat: 0.5 },
  { key: ['5', '1'], beat: 0.5 },
  { key: '1' },
  { key: '1', beat: 0.5 },
  { key: ['5', '6'], beat: 0.5 },
  { key: '6', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: '6', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5' },
  { key: '5', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '3', beat: 0.5 },
  /* --------------------- */
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: ['2', '3'], beat: 2.5 },
  /* --------------------- */
  { key: '3', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '3' },
  { key: '4', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7', beat: 0.5 },
  /* --------------------- */
  { key: '2+', beat: 0.5 },
  { key: '7', beat: 0.5 },
  { key: '1+', beat: 0.5 },
  { key: '1+', beat: 1.25 },
  { key: '0', beat: 0.5 },
  { key: '1+', beat: 0.5 },
  /* --------------------- */
  { key: '1+', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '6', beat: 0.5 },
  { key: '5', beat: 0.25 },
  { key: '4', beat: 0.25 },
  { key: '4', beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  /* --------------------- */
  { key: '4', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '6', beat: 0.5 },
  { key: '1', beat: 0.5 },
  { key: '6', beat: 0.75 },
  { key: '7', beat: 0.25 },
  { key: '7' },
  /* --------------------- */
  { key: ['2', '3'], beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: ['3', '4'], beat: 0.5 },
  { key: '3' },
  { key: '1', beat: 0.5 },
  { key: ['3', '5'], beat: 0.5 },
  { key: '7', beat: 0.5 },
  /* --------------------- */
  { key: '1+', beat: 0.5 },
  { key: '7', beat: 0.5 },
  { key: ['5', '1'], beat: 0.5 },
  { key: '1' },
  { key: '1', beat: 0.5 },
  { key: ['5', '6'], beat: 0.5 },
  { key: '6', beat: 0.5 },
  /* --------------------- */
  { key: '0', beat: 0.5 },
  { key: '6', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5' },
  { key: '5', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '3', beat: 0.5 },
  /* --------------------- */
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: ['2', '3'], beat: 2.5 },
  /* --------------------- */
  { key: '3', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '3' },
  { key: '4', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '7', beat: 0.5 },
  /* --------------------- */
  { key: '2+', beat: 0.5 },
  { key: '7', beat: 0.5 },
  { key: '1+', beat: 0.5 },
  { key: '1+', beat: 1.25 },
  { key: '0', beat: 0.5 },
  { key: '1+', beat: 0.5 },
  /* --------------------- */
  { key: '1+', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '6', beat: 0.5 },
  { key: '5', beat: 0.5 },
  { key: '4', beat: 0.5 },
  { key: '6-', beat: 0.5 },
  { key: '7-', beat: 0.5 },
  /* --------------------- */
  { key: '1', beat: 0.5 },
  { key: '2', beat: 0.5 },
  { key: '3', beat: 0.5 },
  { key: '2', beat: 1.25 },
  { key: ['2', '3'], beat: 0.5 },
  { key: '1', beat: 2.5 },
  /* --------------------- */
  { key: '0', beat: 2 },
  /* --------------------- */
];

// komorebi 未完成，弹到最后对比时间戳主副旋律有0.2-0.4s延迟，等待后续版本更新
const komorebi_beatTime = 100;
const komorebi = {
  main: [
    { key: '6', beat: 0.75, isSection: true },
    { key: '3+', beat: 0.75 },
    { key: '2+', beat: 0.5 },
    { key: ['5+', '7'] },
    { key: '3+' },
    /* --------------------- */
    { key: '2+', beat: 0.75, isSection: true },
    { key: '3+', beat: 0.75 },
    { key: '1+', beat: 0.5 },
    { key: ['5+', '7'] },
    { key: '5' },
    /* --------------------- */
    { key: '6', beat: 0.25, isSection: true },
    { key: '3', beat: 0.25 },
    { key: '3+', beat: 0.75 },
    { key: '3', beat: 0.25 },
    { key: '7', beat: 0.25 },
    { key: '1+', beat: 0.25 },
    { key: '7', beat: 0.75 },
    { key: '5', beat: 0.75 },
    { key: '2', beat: 0.5 },
    /* --------------------- */
    { key: ['3','1','6-'], beat: 2, isSection: true },
    { key: '7-', beat: 2 },
    /* --------------------- */
    { key: '6', beat: 0.75, isSection: true },
    { key: '3+', beat: 0.75 },
    { key: '2+', beat: 0.5 },
    { key: ['5+', '7'] },
    { key: '3+' },
    /* --------------------- */
    { key: '2+', beat: 0.75, isSection: true },
    { key: '3+', beat: 0.75 },
    { key: '1+', beat: 0.5 },
    { key: '7' },
    { key: '5' },
    /* --------------------- */
    { key: '6', beat: 0.25, isSection: true },
    { key: '3', beat: 0.25 },
    { key: '3+', beat: 0.75 },
    { key: '3', beat: 0.25 },
    { key: '7', beat: 0.25 },
    { key: '1+', beat: 0.25 },
    { key: '7', beat: 0.75 },
    { key: '5', beat: 0.75 },
    { key: '2', beat: 0.5 },
    /* --------------------- */
    { key: ['3','1','6-'], beat: 2, isSection: true },
    { key: ['7-','5-','2'], beat: 2 },
    /* --------------------- */
  ],
  vice: [
    { key: '4-', beat: 0.5 , isSection: true},
    { key: '1', beat: 0.5 },
    { key: '3' },
    { key: '5-', beat: 2 },
    /* --------------------- */
    { key: '6-', beat: 0.5, isSection: true },
    { key: '1', beat: 0.5 },
    { key: '3' },
    { key: '3-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '2' },
    /* --------------------- */
    { key: '4--', beat: 0.5, isSection: true },
    { key: '1-', beat: 0.5 },
    { key: '4-' },
    { key: '5--', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '5-' },
    /* --------------------- */
    { key: '6--', beat: 0.5, isSection: true },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '5--', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '5-', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    /* --------------------- */
    { key: '4--', beat: 0.5, isSection: true },
    { key: '1-', beat: 0.5 },
    { key: '3-' },
    { key: '5--', beat: 0.5 },
    { key: '7--', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '7--', beat: 0.5 },
    /* --------------------- */
    { key: '6--', beat: 0.5, isSection: true },
    { key: '1-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '3--', beat: 0.5 },
    { key: '7--', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '7--', beat: 0.5 },
    /* --------------------- */
    { key: '4--', beat: 0.5, isSection: true },
    { key: '1-', beat: 0.5 },
    { key: '4-' },
    { key: '5--', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '7-' },
    /* --------------------- */
    { key: '6--', beat: 0.5, isSection: true },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '5--', beat: 2 },
    /* --------------------- */
  ]
}

// test
// const test_beatTime = 60;
// const test = [
//   { key: ['1', '2'], beat: 1 },
//   { key: '3', beat: 0.5 },
// ]

// 拍子间隔
const beatTime = ((e = 60) => Number((60 / e * 1000).toFixed(3)))(qt_beatTime);

module.exports = {
  musicScore: qt,
  beatTime,
};