const { MusicScore } = require('../../map');
const musicScore = new MusicScore();

// 乐谱名称
musicScore.name = 'flower dance 花之舞';
// Beat Per Minute bpm 拍子数
musicScore.bpm = 80;
// 音乐谱
musicScore.ms = {
  main: [
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '3+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    { key: '6+', beat: 0.5 },
    { key: '2+', beat: 0.5 },
    /* --------------------- */
    { key: '0', beat: 4, new_bpm: 100 },
    /* --------------------- */
    { key: '3', beat: 1 },
    { key: '0', beat: 0.25 },
    { key: '6-', beat: 0.25 },
    { key: '1', beat: 0.25 },
    { key: '3', beat: 0.25 },
    { key: '2', beat: 1 },
    { key: '5', beat: 1 },
    /* --------------------- */
    { key: '2', beat: 0.75 },
    { key: '7', beat: 0.25 },
    { key: '6', beat: 0.75 },
    { key: '5', beat: 0.25 },
    { key: '6', beat: 1 },
    { key: '3+', beat: 1 },
    /* --------------------- */
    { key: '6', beat: 1 },
    { key: '3+', beat: 1 },
    { key: '2+', beat: 0.5 },
    { key: '2+', beat: 0.25 * 2 / 3 },
    { key: '3+', beat: 0.25 * 2 / 3 },
    { key: '2+', beat: 0.25 * 2 / 3 },
    { key: '7', beat: 0.5 },
    { key: '5', beat: 0.5 },
    /* --------------------- */
    { key: '6', beat: 3 },
    { key: '0', beat: 0.5 },
    { key: '3', beat: 0.5 },
    /* --------------------- */
    { key: '3', beat: 1 },
    { key: '0', beat: 0.25 },
    { key: '6-', beat: 0.25 },
    { key: '1', beat: 0.25 },
    { key: '3', beat: 0.25 },
    { key: '2', beat: 1 },
    { key: '5', beat: 1 },
    /* --------------------- */
    { key: '2', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '7', beat: 0.5 },
    { key: '3', beat: 0.25 },
    { key: '1+', beat: 0.25 },
    { key: '3', beat: 0.25 },
    { key: '7', beat: 0.25 },
    { key: '3', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3', beat: 0.25 },
    { key: '5', beat: 0.25 },
    /* --------------------- */
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    /* --------------------- */
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '2+', beat: 0.25 },
    { key: '3+', beat: 0.25 },
    { key: '6', beat: 0.5 },
    { key: '3', beat: 0.5 },
    /* --------------------- */
  ],
  vice: [
    { key: '4-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '4', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '6', beat: 2 },
    /* --------------------- */
    { key: '5-', beat: 0.5 },
    { key: '2', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '7', beat: 2 },
    /* --------------------- */
    { key: '6-', beat: 0.5 },
    { key: '3', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '7', beat: 0.5 },
    { key: '1+', beat: 2 },
    /* --------------------- */
    { key: '0', beat: 4 },
    /* --------------------- */
    { key: '4-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '4', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '6', beat: 2 },
    /* --------------------- */
    { key: '5-', beat: 0.5 },
    { key: '2', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '7', beat: 2 },
    /* --------------------- */
    { key: '6-', beat: 0.5 },
    { key: '3', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '7', beat: 0.5 },
    { key: '1+', beat: 2 },
    /* --------------------- */
    { key: ['6-', '3', '6', '2+', '3+'], beat: 4, new_bpm: 100 },
    /* --------------------- */
    { key: '0', beat: 0.5 },
    { key: '1', beat: 1.5 },
    { key: '5-', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '7-', beat: 1 },
    /* --------------------- */
    { key: '3-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '3', beat: 0.5 },
    { key: '6', beat: 0.5 },
    { key: '3', beat: 0.5 },
    /* --------------------- */
    { key: '4-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '4', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '5-', beat: 0.5 },
    { key: '2', beat: 0.5 },
    { key: '5', beat: 0.5 },
    { key: '2', beat: 0.5 },
    /* --------------------- */
    { key: '6-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '1-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 1 },
    /* --------------------- */
    { key: '4-', beat: 0.5 },
    { key: '1-', beat: 0.5 },
    { key: '4-', beat: 1 },
    { key: '5-', beat: 0.5 },
    { key: '2-', beat: 0.5 },
    { key: '7-', beat: 1 },
    /* --------------------- */
    { key: '3-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '3', beat: 1 },
    { key: '6-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '1', beat: 1 },
    /* --------------------- */
    { key: '4-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '4', beat: 1 },
    { key: '5-', beat: 0.5 },
    { key: '2', beat: 0.5 },
    { key: '5', beat: 1 },
    /* --------------------- */
    { key: '6-', beat: 0.5 },
    { key: '3-', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '7-', beat: 0.5 },
    { key: '1', beat: 0.5 },
    { key: '6-', beat: 0.5 },
    { key: '3-', beat: 1 },
    /* --------------------- */
  ]
};

module.exports = musicScore;